/**
 * generated by Xtext 2.9.0.rc2
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Output</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Output#getSegment <em>Segment</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOutput()
 * @model
 * @generated
 */
public interface Output extends Actions
{
  /**
   * Returns the value of the '<em><b>Segment</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Segment</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Segment</em>' attribute.
   * @see #setSegment(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOutput_Segment()
   * @model
   * @generated
   */
  String getSegment();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Output#getSegment <em>Segment</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Segment</em>' attribute.
   * @see #getSegment()
   * @generated
   */
  void setSegment(String value);

} // Output
